#
# Basic settings.
#
#url: http://localhost:4000
#baseurl: /
#url: http://gloriousft.github.io
baseurl: ""
title: Tianyi's Blog
description: Carpe diem. Seize the day, boys. -- DEAD POETS SOCIETY
avatar: /assets/img/ogp.png
# language: ja
language: zh-CN

#
# Icons
#
icons:
  rss: true
  email:
  github: gloriousft
  bitbucket:
  twitter:
  facebook: tianyi.li.18
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin:  # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  http://stackexchange.com/users/4458189/jason-lee
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: UA-75982423-1
baidu_analytics: 53Vz033ZnI
# e.g. UA-000000-01
disqus: gloriousft
baidu_verification: true

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read More...
str_search: Search
str_recent_posts: Recent Posts
str_show_all_posts: All Posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: false
  facebook: false   # needs ogp.fb.app_id
  hatena: false
ogp:
  image_url: http://qckanemoto.github.io/jekyll-qck-theme/assets/img/ogp.png
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Gems.
#
#gems:
#  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
#  extensions:
#    - autolink
#    - footnotes
#    - smart
#  use_coderay: true
#  coderay:
#    coderay_line_numbers: nil
#  auto_ids: true
#  auto_id_prefix: "id-"
  syntax_highlighter: rouge

#
#Redcarpet should not be used in github
#

#markdown: redcarpet
#redcarpet:
#  extensions: ["autolink", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes", "no_intra_emphasis"]
#highlighter: pygments

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
